#define FOREACH_NODE(FN) \
	FN(ERROR) FN(TYPE) FN(IDENT) FN(LITERAL) \
	\
	FN(OP_UNARY) FN(OP_BINARY) \
	FN(RETURN) FN(WHILE) \
	FN(IF_SINGLE) FN(VAR_SINGLE) \
	\
	FN(INTERNAL) FN(BLOCK) FN(CALL) \
	FN(IF_LIST) FN(VAR_LIST)

#define GENERATE_AST_ENUM(VAL) AST_##VAL,
#define GENERATE_AST_STRS(VAL) #VAL,
